import { useEffect } from "react";
import { useQuery } from "convex/react";
// @ts-expect-error — generated by `convex dev` on first run
import { api } from "@convex/_generated/api.js";
import { useIdentityStore } from "../../state/identityStore.js";
import { useOnlineStore } from "../../state/onlineGameStore.js";
import { UsernameSetup } from "./UsernameSetup.js";
import { LobbyHub } from "./LobbyHub.js";
import { CreateGame } from "./CreateGame.js";
import { JoinGame } from "./JoinGame.js";
import { SeatPicker } from "./SeatPicker.js";
import { OnlineBoard } from "./OnlineBoard.js";
import { OnlineRoundEnd } from "./OnlineRoundEnd.js";
import { OnlineMatchEnd } from "./OnlineMatchEnd.js";

// Routes between the online-mode screens. Resolves a deep-link `?join=ABCD23` query param at
// mount time so a shared link drops the user straight into JoinGame with the code pre-filled.
export function OnlineRoot() {
    const deviceId = useIdentityStore((s) => s.deviceId);
    const displayName = useIdentityStore((s) => s.displayName);
    const screen = useOnlineStore((s) => s.screen);
    const setScreen = useOnlineStore((s) => s.setScreen);

    const me = useQuery(api.users.getUserByDeviceId, { deviceId });

    // If we have a deviceId but no registered display name or user, force the setup screen.
    const needsSetup = displayName.trim().length === 0 || me === null;

    useEffect(() => {
        const url = new URL(window.location.href);
        const joinCode = url.searchParams.get("join");
        if (joinCode !== null && joinCode.length === 6 && !needsSetup) {
            setScreen("join-game");
            url.searchParams.delete("join");
            window.history.replaceState({}, "", url.toString());
        }
    }, [needsSetup, setScreen]);

    if (me === undefined) {
        return <p className="p-4 text-center text-pr-ivory-dim">…</p>;
    }

    if (needsSetup) {
        return <UsernameSetup onDone={() => setScreen("lobby-hub")} />;
    }

    switch (screen) {
        case "name-setup":
            return <UsernameSetup onDone={() => setScreen("lobby-hub")} />;
        case "lobby-hub":
            return <LobbyHub />;
        case "create-game":
            return <CreateGame />;
        case "join-game":
            return <JoinGame />;
        case "seat-picker":
            return <SeatPicker />;
        case "playing":
            return <OnlineBoard />;
        case "round_end":
            return <OnlineRoundEnd />;
        case "match_end":
            return <OnlineMatchEnd />;
    }
}
