import { useMutation, useQuery } from "convex/react";
// @ts-expect-error — generated by `convex dev` on first run
import { api } from "@convex/_generated/api.js";
import { useIdentityStore } from "../../state/identityStore.js";
import { useOnlineStore } from "../../state/onlineGameStore.js";
import { useGameStore } from "../../state/gameStore.js";
import { useT } from "../../i18n/index.js";
import type { RoundOutcomeKind } from "../../engine/types.js";
import type { StringKey } from "../../i18n/strings.js";

const KIND_TITLE: Record<RoundOutcomeKind, StringKey> = {
    domino: "outcomeDomino",
    capicua: "outcomeCapicua",
    chuchazo: "outcomeChuchazo",
    tranca: "outcomeTranca",
};
const KIND_DESC: Record<RoundOutcomeKind, StringKey> = {
    domino: "outcomeDescDomino",
    capicua: "outcomeDescCapicua",
    chuchazo: "outcomeDescChuchazo",
    tranca: "outcomeDescTranca",
};

export function OnlineRoundEnd() {
    const t = useT();
    const lang = useGameStore((s) => s.lang);
    const gameId = useOnlineStore((s) => s.gameId);
    const clearGame = useOnlineStore((s) => s.clearGame);
    const deviceId = useIdentityStore((s) => s.deviceId);
    const me = useQuery(api.users.getUserByDeviceId, { deviceId });
    const view = useQuery(
        api.views.myGameView,
        gameId !== null && me !== null && me !== undefined
            ? { gameId, userId: me._id }
            : "skip",
    );
    const startNextRound = useMutation(api.games.startNextRound);

    if (gameId === null || me === null || me === undefined || view === null || view === undefined) {
        return <p className="p-4 text-center text-pr-ivory-dim">…</p>;
    }
    const o = view.lastOutcome;
    if (o === null) return <p className="p-4 text-center text-pr-ivory-dim">…</p>;
    const isHost = view.hostUserId === me._id;
    const teamAccent = o.winningTeam === "A" ? "text-pr-blue" : "text-pr-red";
    return (
        <div className="flex flex-1 flex-col items-center justify-center gap-6 text-center">
            <div className="space-y-1">
                <p className="text-xs uppercase tracking-widest text-pr-ivory-dim">
                    {t("round")} {view.round}
                </p>
                <h2 className={`font-display text-5xl ${teamAccent}`}>
                    {t(KIND_TITLE[o.kind as RoundOutcomeKind])}
                </h2>
                <p className="text-sm text-pr-ivory-dim">
                    {t(KIND_DESC[o.kind as RoundOutcomeKind])}
                </p>
            </div>
            <p className="font-display text-3xl text-pr-ivory">
                +{o.points} {t("pointsToTeam", { team: o.winningTeam })}
            </p>
            <div className="flex gap-3">
                {isHost && (
                    <button
                        type="button"
                        onClick={() => void startNextRound({ gameId, callerUserId: me._id })}
                        className="rounded-xl bg-pr-blue px-6 py-2 font-display text-pr-white shadow"
                    >
                        {t("nextRound")}
                    </button>
                )}
                <button
                    type="button"
                    onClick={clearGame}
                    className="rounded-xl border border-pr-coal-soft px-6 py-2 text-pr-ivory-dim hover:text-pr-ivory"
                >
                    {t("quitToMenu")}
                </button>
            </div>
            {!isHost && (
                <p className="text-xs text-pr-ivory-dim">
                    {lang === "es"
                        ? "Esperando que el anfitrión comience la próxima ronda…"
                        : "Waiting for host to start next round…"}
                </p>
            )}
        </div>
    );
}
