import { useState } from "react";
import { useMutation } from "convex/react";
// @ts-expect-error — generated by `convex dev` on first run
import { api } from "@convex/_generated/api.js";
import { useIdentityStore } from "../../state/identityStore.js";
import { useT } from "../../i18n/index.js";

// First-time setup: ask for a display name and register a user row keyed by the deviceId.
export function UsernameSetup({ onDone }: { onDone: () => void }) {
    const t = useT();
    const deviceId = useIdentityStore((s) => s.deviceId);
    const setDisplayName = useIdentityStore((s) => s.setDisplayName);
    const createOrGetUser = useMutation(api.users.createOrGetUser);
    const [name, setName] = useState("");
    const [submitting, setSubmitting] = useState(false);

    const submit = async () => {
        const trimmed = name.trim();
        if (trimmed.length < 1 || trimmed.length > 24) return;
        setSubmitting(true);
        try {
            await createOrGetUser({ deviceId, displayName: trimmed });
            setDisplayName(trimmed);
            onDone();
        } finally {
            setSubmitting(false);
        }
    };

    return (
        <div className="flex flex-1 flex-col items-center justify-center gap-6 text-center">
            <h2 className="font-display text-3xl text-pr-ivory">
                {t("language") === "Idioma" ? "Tu nombre" : "Your name"}
            </h2>
            <p className="text-sm text-pr-ivory-dim">
                {t("language") === "Idioma"
                    ? "Cómo te van a ver los otros jugadores."
                    : "How other players see you."}
            </p>
            <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                onKeyDown={(e) => {
                    if (e.key === "Enter") void submit();
                }}
                maxLength={24}
                placeholder="Joel"
                autoFocus
                className="w-64 rounded-xl border border-pr-coal-soft bg-pr-coal-soft/40 px-4 py-2 text-center font-display text-xl text-pr-ivory placeholder:text-pr-ivory-dim/50 focus:border-pr-coqui focus:outline-none"
            />
            <button
                type="button"
                onClick={() => void submit()}
                disabled={submitting || name.trim().length < 1}
                className="rounded-xl bg-pr-blue px-8 py-2 font-display text-pr-white shadow disabled:opacity-40"
            >
                {submitting ? "..." : t("language") === "Idioma" ? "Continuar" : "Continue"}
            </button>
        </div>
    );
}
